project:
  type: website
  
website:
  title: "Myblog"
  navbar:
    right:
      - about.qmd
      - listing.qmd
      - icon: github
        href: https://github.com/rafinflaziz
      - icon: twitter
        href: https://twitter.com/rafinflaziz
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



